cargo-features = ["codegen-backend"]

[workspace]
members = ["tree_sitters", "misc"]
resolver = "2"

[profile.dev]
debug = 0
codegen-backend = "cranelift"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
